# Generated CI/CD Pipeline YAML
# This YAML is compatible with GitHub Actions

# Pipeline: tutorial3
name: tutorial3

on:
  workflow_dispatch:

jobs:
  build_test:
    # Build and test the application
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
            - name: command_90745
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                        node-version: '18'
            - name: Install dependenciesencies
              uses: actions/setup-node@v3
              with:
                        node-version: '18'
            - name: Install dependencies
              run: yarn install
            - name: Run tests
              run: yarn test
  deploy:
    # Build and test the application
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
            - name: command_87597
              uses: actions/checkout@v4
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
    needs: ["build_test"]
